name: codecov

on:
  push:
    branches: ["main"]
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install lcov
        run: sudo apt-get install lcov

      - name: Make build directory
        run: mkdir build

      - name: Configure CMake with Code Coverage
        working-directory: build
        run: cmake -DCODE_COVERAGE=ON ..

      - name: Run build
        run: ./build.sh

      - name: Run tests
        run: ./test.sh
      
      - name: Generate coverage report
        working-directory: build
        run: |
          lcov --capture --directory . --output-file coverage.info
          # had to comment out the ignore below
          # lcov --remove coverage.info '/usr/*' '*/lib/Catch2/src/*' --output-file coverage.info
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v1
        with:
            file: ./build/coverage.info
          #env:
          #  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
