name: Generate Doxygen Documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Doxygen
      run: sudo apt-get install doxygen

    - name: Generate Documentation
      run: |
        cd src
        doxygen
        
    - name: Commit and push if there are changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Add generated Doxygen documentation" || echo "No changes to commit"
        git push
